### PR TITLE
WIP tests & docs codemod escape route

### LINKED ISSUE #6: document escape route (codemod)
As a potential user, it may be a difficult decision to adopt this style of writing tests if it means you're forced to keep using this plugin unless you rewrite all your tests.

A well and visibly documented escape hatch using babel and this plugin as a codemod could make the decision somewhat easier.

This should probably wait until #3 is implemented and then document which of the config options introduced can be relevant for the codemod.

### PR DESCRIPTION
**Pull request by jeysal**
closes #6

### CODE REVIEW

**Comment by jeysal** [comment]
@succcubbus can you try to set up a project with tests that use the plugin and then try to follow the escape route instructions in this PR's readme so we can see if the tests still work for you with this guide and whether there's anything unclear in it?

**Comment by succcubbus** [comment]
I followed the steps as described but can't get it to work.
I figured I have to install babel-cli globally so I did.
Then I created a config.json with the given content and ran the command on this file: https://github.com/succcubbus/horrible-downloader/blob/release-parsing/test/release-parser.test.js
All that happened was that it removed the trailing colon on line 7.

**Comment by succcubbus** [comment]
Yes, the test are running successfully with the plugin.

**Comment by jeysal** [comment]
Thanks. I'm a bit busy the next few days, so I'll get back to you ~next week.

**Comment by jeysal** [comment]
I've updated the readme section to clarify the Babel installation thing.

I haven't had much time to dive into your example repo yet, but I've noticed that it uses the Babel 6 stable release, which is not supported on `babel-plugin-spock@"> 0.1.0"`.
Can you try if updating the repo to the current Babel 7 beta changes anything?

**Comment by jeysal** [comment]
just fixed another error in the documentation:
`--config-file config.json` => `--config-file ./config.json`

**Comment by jeysal** [comment]
also, I just noticed #38 wasn't even in a release yet 🤦
published 0.5.0

**Comment by jeysal** [comment]
I can confirm that in the current state of https://github.com/succcubbus/horrible-downloader/commit/131c394a34808b1549403a1a546639d2b9638b08, the codemod does not work.
However, after upgrading to babel 7, it works for me.
Can you grab the babel 7 upgrade from [my fork](https://github.com/jeysal/horrible-downloader/tree/release-parsing) and try to follow the steps again? Thank you :)

**Comment by succcubbus** [comment]
I got the escape route to work, though I would expect the `expect: ` labels to be removed as well.
The npx command line didn't work until i ran `yarn global add @babel/cli@latest @babel/core@latest`. I'm not sure if it's implied to have these installed though.

**Comment by jeysal** [comment]
Removal of the `expect` labels is tracked in #47. I have now also added it to the 1.0.0 milestone because I agree that this is pretty essential.
Thanks, I'll add `@babel/core` to the global install instructions!

**Pull request merged**
